/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Record = "run";
export type SchemaVersion = 1;
export type Id = string;
export type Name = string;
export type Source = "python" | "codex" | "claude-code" | "factory" | "n8n" | "custom" | "demo" | "example" | "clip";
export type Version = string;
export type StartedAt = string;
export type Model = string | null;
export type Provider = string | null;
export type Status = "running" | "success" | "failed" | "cancelled" | "incomplete";
export type DurationMs = number | null;
export type Warnings = string[];
export type Record1 = "event";
export type Id1 = string;
export type RunId = string;
export type Seq = number;
export type Kind =
  "model.start" | "model.end" | "tool.start" | "tool.end" | "context" | "memory" | "error" | "message" | "run.end";
export type Lane = "model" | "tools" | "context" | "memory" | "errors";
export type Name1 = string;
export type Timestamp = string;
export type ElapsedMs = number | null;
export type DurationMs1 = number | null;
export type SpanId = string | null;
export type ParentId = string | null;
export type SnapshotId = string | null;
export type Status1 = "running" | "success" | "failed" | "cancelled" | "unknown";
export type Provenance = "captured" | "imported" | "fixture" | "derived";
export type Partial = boolean;
/**
 * @maxItems 10000
 */
export type Events = Event[];
export type Record2 = "note";
export type Id2 = string;
export type RunId1 = string;
export type EventId = string | null;
export type ElapsedMs1 = number;
export type Text = string;
export type CreatedAt = string;
export type UpdatedAt = string;
/**
 * @maxItems 1000
 */
export type Notes = Note[];

export interface Tape {
  run: Run;
  events: Events;
  notes?: Notes;
}
export interface Run {
  record?: Record;
  schema_version?: SchemaVersion;
  id?: Id;
  name: Name;
  source?: Source;
  version?: Version;
  started_at?: StartedAt;
  model?: Model;
  provider?: Provider;
  status?: Status;
  duration_ms?: DurationMs;
  capabilities?: Capabilities;
  configuration?: Configuration;
  warnings?: Warnings;
}
export interface Capabilities {
  [k: string]: string;
}
export interface Configuration {
  [k: string]: unknown;
}
export interface Event {
  record?: Record1;
  id?: Id1;
  run_id: RunId;
  seq: Seq;
  kind: Kind;
  lane: Lane;
  name: Name1;
  timestamp?: Timestamp;
  elapsed_ms?: ElapsedMs;
  duration_ms?: DurationMs1;
  span_id?: SpanId;
  parent_id?: ParentId;
  snapshot_id?: SnapshotId;
  status?: Status1;
  provenance?: Provenance;
  partial?: Partial;
  data?: Data;
}
export interface Data {
  [k: string]: unknown;
}
export interface Note {
  record?: Record2;
  id?: Id2;
  run_id: RunId1;
  event_id?: EventId;
  elapsed_ms: ElapsedMs1;
  text: Text;
  created_at?: CreatedAt;
  updated_at?: UpdatedAt;
}
