/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ExcerptId = number;
/**
 * @maxItems 4
 */
export type Quotes = EvidenceQuote[];
export type ExcerptId1 = number;
export type Question = string;
export type WhyUnknown = string;
/**
 * @maxItems 3
 */
export type Questions = InvestigationQuestion[];
/**
 * @maxItems 3
 */
export type MissingEvidence = string[];
/**
 * @minItems 1
 * @maxItems 3
 */
export type VerificationSteps = string[];

export interface AnalysisDraft {
  quotes: Quotes;
  questions: Questions;
  missing_evidence: MissingEvidence;
  verification_steps: VerificationSteps;
}
export interface EvidenceQuote {
  excerpt_id: ExcerptId;
}
export interface InvestigationQuestion {
  excerpt_id: ExcerptId1;
  question: Question;
  why_unknown: WhyUnknown;
}
